### ISSUE TITLE
预备工作-汇编编程

### ISSUE THREAD

**Issue by KaiserTT** [KaiserTT/NKU_Compiler_24Fall#5]
设计几个 SysY 程序，编写等价的 ARM/RISC-V 汇编程序，用汇编器生成可执行程序，调试通过、能正常运行得到正确结果

**Comment by Ethan2k04** [comment]
程序1-实现了输出“Hello Compiler”的功能（参见ethan_branch下的asm_riscv64/hello_world.s）

**Comment by Ethan2k04** [comment]
程序2-实现了接收用户输入，输出阶乘的功能
程序3-实现了接收用户输入迭代次数，输出Fibonacci数列结果的功能
